# Generated by Django 5.0.4 on 2024-05-18 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Terreto',
            new_name='Terreno',
        ),
    ]
